Customized dotfiles to preferences

diff --git a/installscript b/installscript
--- a/installscript
+++ b/installscript
@@ -9,6 +9,23 @@ echo '-----------------'
 rm -rf $HOME/.oh-my-zsh
 curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
 
+# Install Powerline Fonts
+echo 'Install Powerline Fonts'
+echo '-----------------------'
+rm -rf $HOME/.powerline-fonts
+cd $HOME
+git clone https://github.com/powerline/fonts.git --depth=1 .powerline-fonts
+cd .powerline-fonts
+./install.sh
+cd $HOME/.dotfiles/
+
+# Install Powerlevel 10K
+echo 'Install Powerlevel 10K'
+echo '----------------------'
+cd $HOME/.oh-my-zsh/themes/
+git clone https://github.com/romkatv/powerlevel10k.git
+cd $HOME/.dotfiles
+
 # Add global gitignore
 ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
 git config --global core.excludesfile $HOME/.global-gitignore
@@ -18,60 +35,60 @@ rm $HOME/.zshrc
 ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
 
 # Symlink vim prefs
-rm $HOME/.vimrc
-ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
-rm $HOME/.vim
-ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim
+#rm $HOME/.vimrc
+#ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
+#rm $HOME/.vim
+#ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim
 
 # Symlink the Mackup config
 ln -s $HOME/.dotfiles/macos/.mackup.cfg $HOME/.mackup.cfg
 
 # Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
-cd ~/.oh-my-zsh/themes/
-git checkout d6a36b1 agnoster.zsh-theme
+#cd ~/.oh-my-zsh/themes/
+#git checkout d6a36b1 agnoster.zsh-theme
 
 # Activate z
-cd ~/.dotfiles/shell
-chmod +x z.sh
+#cd ~/.dotfiles/shell
+#chmod +x z.sh
 
-echo 'Configure npm'
-echo '-------------'
+#echo 'Configure npm'
+#echo '-------------'
 # Create a directory for global packages and tell npm where to store globally installed packages
-mkdir "${HOME}/.npm-packages"
-npm config set prefix "${HOME}/.npm-packages"
+#mkdir "${HOME}/.npm-packages"
+#npm config set prefix "${HOME}/.npm-packages"
 
-echo 'Install composer'
-echo '----------------'
-EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
-php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
-if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
-then
-    >&2 echo 'ERROR: Invalid installer checksum'
-    rm composer-setup.php
-    exit 1
-fi
-php composer-setup.php
-rm composer-setup.php
-mv composer.phar /usr/local/bin/composer
+#echo 'Install composer'
+#echo '----------------'
+#EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
+#php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+#ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+#if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
+#then
+#    >&2 echo 'ERROR: Invalid installer checksum'
+#    rm composer-setup.php
+#    exit 1
+#fi
+#php composer-setup.php
+#rm composer-setup.php
+#mv composer.phar /usr/local/bin/composer
 
 echo 'Install homebrew'
 echo '----------------'
 echo install homebrew
 sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
-ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 
-echo 'Install node'
-echo '------------'
-brew install node@8
+#echo 'Install node'
+#echo '------------'
+#brew install node@8
 
-echo 'Install pkg-config'
-echo '------------------'
-brew install pkg-config
+#echo 'Install pkg-config'
+#echo '------------------'
+#brew install pkg-config
 
 echo 'Install wget'
 echo '------------'
-brew install wget --overwrite
+brew install wget
 
 echo 'Install httpie'
 echo '--------------'
@@ -93,70 +110,82 @@ echo 'Install doctl'
 echo '-------------'
 brew install doctl
 
-echo 'Install brew-cask'
-echo '-----------------'
-brew tap caskroom/cask
-brew install brew-cask
+#echo 'Install brew-cask'
+#echo '-----------------'
+#brew tap caskroom/cask
+#brew install brew-cask
 
 echo 'Install some nice quicklook plugins'
 echo '-----------------------------------'
-brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip webp-quicklook suspicious-package
+brew install --cask qlcolorcode 
+brew install --cask qlstephen
+brew install --cask qlmarkdown
+brew install --cask quicklook-json
+brew install --cask qlprettypatch
+brew install --cask quicklook-csv
+brew install --cask betterzip
+brew install --cask webpquicklook
+brew install --cask suspicious-package
 
-echo 'Install php'
-echo '-----------'
-brew install php@7.4
-brew install php@8.0
+#echo 'Install php'
+#echo '-----------'
+#brew install php@7.4
+#brew install php@8.0
 
 
-echo 'Install imagemagick'
-echo '-------------------'
-brew install imagemagick
+#echo 'Install imagemagick'
+#echo '-------------------'
+#brew install imagemagick
 
-echo 'Install imagick'
-echo '---------------'
-pecl install imagick
+#echo 'Install imagick'
+#echo '---------------'
+#pecl install imagick
 
-echo 'Install memcached'
-echo '-----------------'
-pecl install memcached
+#echo 'Install memcached'
+#echo '-----------------'
+#pecl install memcached
 
-echo 'Install xdebug'
-echo '--------------'
-pecl install xdebug
+#echo 'Install xdebug'
+#echo '--------------'
+#pecl install xdebug
 
-echo 'Install redis'
-echo '-------------'
-pecl install redis
+#echo 'Install redis'
+#echo '-------------'
+#pecl install redis
 
-echo 'Install laravel envoy'
-echo '---------------------'
-composer global require "laravel/envoy=~2.0"
+#echo 'Install laravel envoy'
+#echo '---------------------'
+#composer global require "laravel/envoy=~2.0"
 
-echo 'Install phpunit-watcher'
-echo '-----------------------'
-composer global require spatie/phpunit-watcher
+#echo 'Install phpunit-watcher'
+#echo '-----------------------'
+#composer global require spatie/phpunit-watcher
 
-echo 'Install mixed-content-scanner-cli'
-echo '---------------------------------'
-composer global require spatie/mixed-content-scanner-cli
+#echo 'Install mixed-content-scanner-cli'
+#echo '---------------------------------'
+#composer global require spatie/mixed-content-scanner-cli
 
-echo 'Install laravel valet'
-echo '---------------------'
-composer global require laravel/valet
-valet install
+#echo 'Install laravel valet'
+#echo '---------------------'
+#composer global require laravel/valet
+#valet install
 
-echo 'Install mysql'
-echo '-------------'
-brew install mysql
-brew services start mysql
+#echo 'Install mysql'
+#echo '-------------'
+#brew install mysql
+#brew services start mysql
 
-echo 'Install yarn'
-echo '------------'
-brew install yarn
+#echo 'Install yarn'
+#echo '------------'
+#brew install yarn
 
-echo 'Install ghostscript'
-echo '-------------------'
-brew install ghostscript
+#echo 'Install ghostscript'
+#echo '-------------------'
+#brew install ghostscript
+
+echo 'Install RsyncOSX'
+echo '----------------'
+brew install --cask rsyncosx
 
 echo 'Install mackup'
 echo '--------------'
